Added environment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,6 +8,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    environment: 'Andresa Test'
 
     steps:
       - name: Checkout repository
@@ -18,6 +19,15 @@ jobs:
           echo "${{ secrets.OPENVPN_CONFIG }}" | base64 -d > config.ovpn
           docker run -v $PWD:/vpn -d --cap-add=NET_ADMIN --device /dev/net/tun --name vpn dperson/openvpn-client -f "" -r 192.168.1.0/24
           sleep 10  # give the VPN some time to establish connection
+
+      - name: Check VPN connection
+        run: |
+          if ping -c 1 -W 10 <vpn_server_ip>; then
+              echo "VPN connection successful"
+          else
+              echo "VPN connection failed"
+              exit 1
+          fi
 
       - name: Execute commands over ssh
         uses: appleboy/ssh-action@master
